/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PraPertemuan;

import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author hp14s
 */
public class MainFrame extends javax.swing.JFrame {
    private final JFileChooser fileChooser;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        fileChooser = new JFileChooser();
        fileChooser.setPreferredSize(new Dimension(600, 350));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Text Document", "txt"));
        fileChooser.setAcceptAllFileFilterUsed(true);
        
        inputTextArea.setLineWrap(true);
        inputTextArea.setWrapStyleWord(true);
        
        getContentPane().setBackground(new Color(51,51,51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        prosesButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        karakterLabel = new javax.swing.JLabel();
        barisLabel = new javax.swing.JLabel();
        vokalLabel = new javax.swing.JLabel();
        konsonanLabel = new javax.swing.JLabel();
        karakterTextField = new javax.swing.JTextField();
        barisTextField = new javax.swing.JTextField();
        vokalTextField = new javax.swing.JTextField();
        konsonanTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Note-Stis");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        inputTextArea.setBackground(new java.awt.Color(0, 0, 0));
        inputTextArea.setColumns(20);
        inputTextArea.setForeground(new java.awt.Color(255, 255, 255));
        inputTextArea.setLineWrap(true);
        inputTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(inputTextArea);

        prosesButton.setBackground(new java.awt.Color(51, 51, 51));
        prosesButton.setForeground(new java.awt.Color(255, 255, 255));
        prosesButton.setText("Proses Text");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(51, 51, 51));
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear Text Area");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(51, 51, 51));
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save Proses Text (*.txt)");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        karakterLabel.setForeground(new java.awt.Color(255, 255, 255));
        karakterLabel.setText("Jumlah Karakter (diluar spasi) :");

        barisLabel.setForeground(new java.awt.Color(255, 255, 255));
        barisLabel.setText("Jumlah Baris :");

        vokalLabel.setForeground(new java.awt.Color(255, 255, 255));
        vokalLabel.setText("Jumlah Huruf Vokal :");

        konsonanLabel.setForeground(new java.awt.Color(255, 255, 255));
        konsonanLabel.setText("Jumlah Huruf Konsonan :");

        karakterTextField.setEditable(false);
        karakterTextField.setBackground(new java.awt.Color(0, 0, 0));
        karakterTextField.setForeground(new java.awt.Color(255, 255, 255));
        karakterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karakterTextFieldActionPerformed(evt);
            }
        });

        barisTextField.setEditable(false);
        barisTextField.setBackground(new java.awt.Color(0, 0, 0));
        barisTextField.setForeground(new java.awt.Color(255, 255, 255));
        barisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barisTextFieldActionPerformed(evt);
            }
        });

        vokalTextField.setEditable(false);
        vokalTextField.setBackground(new java.awt.Color(0, 0, 0));
        vokalTextField.setForeground(new java.awt.Color(255, 255, 255));
        vokalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vokalTextFieldActionPerformed(evt);
            }
        });

        konsonanTextField.setEditable(false);
        konsonanTextField.setBackground(new java.awt.Color(0, 0, 0));
        konsonanTextField.setForeground(new java.awt.Color(255, 255, 255));
        konsonanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konsonanTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(prosesButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clearButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(karakterLabel)
                            .addGap(18, 18, 18)
                            .addComponent(karakterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(barisLabel)
                            .addGap(106, 106, 106)
                            .addComponent(barisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(vokalLabel)
                                .addGap(18, 18, 18)
                                .addComponent(vokalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(konsonanLabel)
                                .addGap(18, 18, 18)
                                .addComponent(konsonanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(24, 24, 24)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(242, 242, 242)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prosesButton)
                        .addComponent(clearButton)
                        .addComponent(saveButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(karakterLabel)
                        .addComponent(karakterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vokalLabel)
                        .addComponent(vokalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barisLabel))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(konsonanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(konsonanLabel)))
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));

        jMenu1.setText("File");

        openMenuItem.setBackground(new java.awt.Color(51, 51, 51));
        openMenuItem.setText("Open (*.txt)");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        saveMenuItem.setText("Save (*.txt)");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        int returnValue = fileChooser.showOpenDialog(this);
        File f = fileChooser.getSelectedFile();
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
                FileReader fr = new FileReader(f);
                int i;
                String teks = "";
                
                while ((i = fr.read()) != -1) {
                    teks += (char)i;
                    inputTextArea.setText(teks);
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Tidak ada file yang dipilih");
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        String teks = inputTextArea.getText();
        
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("outputText.txt"));
            
            bw.write(teks);
            JOptionPane.showMessageDialog(this, "Text berhasil disimpan dalam file outputText.txt");
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void konsonanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konsonanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konsonanTextFieldActionPerformed

    private void vokalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vokalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vokalTextFieldActionPerformed

    private void barisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barisTextFieldActionPerformed

    private void karakterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karakterTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karakterTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String proses = "Hasil Proses Text\n"
        + "=================\n"
        + "Jumlah Karakter (diluar spasi) : " + karakterTextField.getText()
        + "\nJumlah Baris : " + barisTextField.getText()
        + "\nJumlah Huruf Vokal : " + vokalTextField.getText()
        + "\nJumlah Huruf Konsonan : " + konsonanTextField.getText();

        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("outputProses.txt"));

            bw.write(proses);
            JOptionPane.showMessageDialog(this, "Hasil proses text berhasil disimpan dalam file outputProses.txt");
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        inputTextArea.setText("");
        karakterTextField.setText("");
        barisTextField.setText("");
        vokalTextField.setText("");
        konsonanTextField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        // TODO add your handling code here:
        String text = inputTextArea.getText();
        String textKecil = text.toLowerCase();
        int jumlahKarakter = 0;
        int jumlahBaris = 1;
        int jumlahVokal = 0;
        int jumlahKonsonan = 0;

        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) != ' ' && text.charAt(i) != '\n')
            jumlahKarakter++;
            if (textKecil.charAt(i) == 'a' || textKecil.charAt(i) == 'i'
                || textKecil.charAt(i) == 'u' || textKecil.charAt(i) == 'e'
                || textKecil.charAt(i) == 'o')
            jumlahVokal++;
            else if (textKecil.charAt(i) >= 'a' && textKecil.charAt(i) <= 'z')
            jumlahKonsonan++;
        }

        if (text.length() == 0)
        jumlahBaris = 0;
        else {
            jumlahBaris = inputTextArea.getPreferredSize().height / inputTextArea.getFontMetrics(inputTextArea.getFont()).getHeight();
        }

        karakterTextField.setText(String.valueOf(jumlahKarakter));
        barisTextField.setText(String.valueOf(jumlahBaris));
        vokalTextField.setText(String.valueOf(jumlahVokal));
        konsonanTextField.setText(String.valueOf(jumlahKonsonan));
    }//GEN-LAST:event_prosesButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame view = new MainFrame();
                view.setVisible(true);                                       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barisLabel;
    private javax.swing.JTextField barisTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel karakterLabel;
    private javax.swing.JTextField karakterTextField;
    private javax.swing.JLabel konsonanLabel;
    private javax.swing.JTextField konsonanTextField;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton prosesButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel vokalLabel;
    private javax.swing.JTextField vokalTextField;
    // End of variables declaration//GEN-END:variables
}
